"""
Sphinx extension to generate backward-compatible redirect map for split LangRef.

When LangRef.rst was split into multiple sub-pages under LangRef/,
old links to LangRef.html#anchor need to be redirected to the correct
sub-page. This extension scans the generated HTML files after build
and produces a redirect map that is embedded into LangRef.html via
JavaScript.
"""

import json
import re
from pathlib import Path

from sphinx.application import Sphinx

# IDs to exclude from the redirect map (generic/framework IDs)
_EXCLUDED_IDS = frozenset({
    "top",
    "searchbox",
    "search",
    "indices-and-tables",
})

# Pattern for auto-generated numeric IDs (e.g., id1, id2, id14)
_AUTO_ID_RE = re.compile(r"^id\d+$")


def collect_ids_from_html(html_path: str) -> list:
    """Extract meaningful id attributes from an HTML file using regex."""
    with open(html_path, "r", encoding="utf-8") as f:
        content = f.read()
    # Match id="..." attributes in HTML tags
    ids = re.findall(r'\bid="([^"]+)"', content)
    # Also match name="..." for old-style anchors
    ids += re.findall(r'\bname="([^"]+)"', content)
    # Filter out auto-generated and generic IDs
    meaningful_ids = [
        aid
        for aid in set(ids)
        if aid not in _EXCLUDED_IDS and not _AUTO_ID_RE.match(aid)
    ]
    return meaningful_ids


def on_build_finished(app: Sphinx, exception: Exception) -> None:
    """After build, scan LangRef/*.html and generate redirect map."""
    if exception:
        return

    if app.builder.name != "html":
        return

    outdir = Path(app.outdir)
    langref_dir = outdir / "LangRef"

    if not langref_dir.exists():
        return

    # Collect all IDs from LangRef sub-pages
    redirect_map = {}
    for html_file in sorted(langref_dir.glob("*.html")):
        relative_path = f"LangRef/{html_file.name}"
        ids = collect_ids_from_html(str(html_file))
        for anchor_id in ids:
            # First sub-page wins (preserves natural ordering)
            if anchor_id not in redirect_map:
                redirect_map[anchor_id] = relative_path

    if not redirect_map:
        return

    # Generate redirect JavaScript
    js_content = (
        "// Auto-generated by langref_redirect Sphinx extension.\n"
        "// Maps old LangRef.html#anchor links to the correct sub-page.\n"
        "var LANGREF_REDIRECT_MAP = "
        + json.dumps(redirect_map, separators=(",", ":"))
        + ";\n"
    )

    # Write redirect map JS file
    static_dir = outdir / "_static"
    static_dir.mkdir(exist_ok=True)
    js_path = static_dir / "langref_redirect_map.js"
    js_path.write_text(js_content, encoding="utf-8")

    # Inject script tag into LangRef.html if not already present
    langref_html = outdir / "LangRef.html"
    if langref_html.exists():
        content = langref_html.read_text(encoding="utf-8")
        if "langref_redirect_map.js" not in content:
            # Add script tag before </body>
            script_tag = (
                '<script src="_static/langref_redirect_map.js"></script>\n'
                "<script>\n"
                "(function() {\n"
                "  var hash = window.location.hash;\n"
                "  if (!hash || hash === '#') return;\n"
                "  var anchor = hash.substring(1);\n"
                "  if (typeof LANGREF_REDIRECT_MAP === 'undefined') return;\n"
                "  var target = LANGREF_REDIRECT_MAP[anchor];\n"
                "  if (!target) {\n"
                "    // Try normalizing underscores to hyphens (Sphinx convention)\n"
                "    target = LANGREF_REDIRECT_MAP[anchor.replace(/_/g, '-')];\n"
                "  }\n"
                "  if (target) {\n"
                "    window.location.replace(target + hash);\n"
                "  }\n"
                "})();\n"
                "</script>\n"
            )
            content = content.replace("</body>", script_tag + "</body>")
            langref_html.write_text(content, encoding="utf-8")


def setup(app: Sphinx) -> dict:
    app.connect("build-finished", on_build_finished)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
